x-veld:
  code:
    description: "custom evaluation logic on GloVe word embeddings."
    topic:
      - "NLP"
      - "Machine Learning"
      - "Evaluation"

    input:
      - volume: /veld/input/model/
        environment_var: in_vector_file
        file_type: "GloVe model"
        content:
          - "NLP model"
          - "Word Embeddings model"
      - volume: /veld/input/model/
        environment_var: in_model_metadata_file
        file_type: "yaml"
        content: "metadata"
      - volume: /veld/input/eval_data/
        environment_var: in_eval_gold_data_file
        file_type: "yaml"
        content: "NLP gold data"

    output:
      - volume: /veld/output/summary/
        environment_var: out_eval_summary_file
        file_type: "yaml"
        description: ""
      - volume: /veld/output/log/
        environment_var: out_eval_log_file
        file_type: "txt"
        content: "log"

    config:
      - environment_var: model_id
        description: "id of the model"
        var_type: "str"

services:
  veld_eval_glove:
    build: 
      context: .
      dockerfile: ./build_glove.dockerfile
    command: python3 eval_glove.py
    volumes:
      - ./src/:/veld/code/:z
    environment:
      in_1_vector_file: null
      model_id: null
      in_1_model_metadata_file: null
      in_2_eval_gold_data_file: null
      out_1_eval_summary_file: null
      out_2_eval_log_file: null

